// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: Gomoku.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board       []int32 `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`                         // 0: empty, 1: black, 2: white
	CurrentTurn int32   `protobuf:"varint,2,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"` // 1: black, 2: white
	IsGameOver  bool    `protobuf:"varint,3,opt,name=is_game_over,json=isGameOver,proto3" json:"is_game_over,omitempty"`
	Winner      int32   `protobuf:"varint,4,opt,name=winner,proto3" json:"winner,omitempty"` // 0: none, 1: black, 2: white
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *GameState) GetIsGameOver() bool {
	if x != nil {
		return x.IsGameOver
	}
	return false
}

func (x *GameState) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

type PlaceStone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string    `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *PlaceStone) Reset() {
	*x = PlaceStone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceStone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceStone) ProtoMessage() {}

func (x *PlaceStone) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceStone.ProtoReflect.Descriptor instead.
func (*PlaceStone) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceStone) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlaceStone) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type GameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlackPlayer string `protobuf:"bytes,1,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	WhitePlayer string `protobuf:"bytes,2,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{3}
}

func (x *GameStart) GetBlackPlayer() string {
	if x != nil {
		return x.BlackPlayer
	}
	return ""
}

func (x *GameStart) GetWhitePlayer() string {
	if x != nil {
		return x.WhitePlayer
	}
	return ""
}

type RequestGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *RequestGame) Reset() {
	*x = RequestGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGame) ProtoMessage() {}

func (x *RequestGame) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGame.ProtoReflect.Descriptor instead.
func (*RequestGame) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{4}
}

func (x *RequestGame) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LoginMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{5}
}

func (x *LoginMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LogoutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *LogoutMessage) Reset() {
	*x = LogoutMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutMessage) ProtoMessage() {}

func (x *LogoutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutMessage.ProtoReflect.Descriptor instead.
func (*LogoutMessage) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GomokuMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*GomokuMessage_GameState
	//	*GomokuMessage_PlaceStone
	//	*GomokuMessage_GameStart
	//	*GomokuMessage_RequestGame
	//	*GomokuMessage_Login
	//	*GomokuMessage_Logout
	Message isGomokuMessage_Message `protobuf_oneof:"message"`
}

func (x *GomokuMessage) Reset() {
	*x = GomokuMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gomoku_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GomokuMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GomokuMessage) ProtoMessage() {}

func (x *GomokuMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Gomoku_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GomokuMessage.ProtoReflect.Descriptor instead.
func (*GomokuMessage) Descriptor() ([]byte, []int) {
	return file_Gomoku_proto_rawDescGZIP(), []int{7}
}

func (m *GomokuMessage) GetMessage() isGomokuMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *GomokuMessage) GetGameState() *GameState {
	if x, ok := x.GetMessage().(*GomokuMessage_GameState); ok {
		return x.GameState
	}
	return nil
}

func (x *GomokuMessage) GetPlaceStone() *PlaceStone {
	if x, ok := x.GetMessage().(*GomokuMessage_PlaceStone); ok {
		return x.PlaceStone
	}
	return nil
}

func (x *GomokuMessage) GetGameStart() *GameStart {
	if x, ok := x.GetMessage().(*GomokuMessage_GameStart); ok {
		return x.GameStart
	}
	return nil
}

func (x *GomokuMessage) GetRequestGame() *RequestGame {
	if x, ok := x.GetMessage().(*GomokuMessage_RequestGame); ok {
		return x.RequestGame
	}
	return nil
}

func (x *GomokuMessage) GetLogin() *LoginMessage {
	if x, ok := x.GetMessage().(*GomokuMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *GomokuMessage) GetLogout() *LogoutMessage {
	if x, ok := x.GetMessage().(*GomokuMessage_Logout); ok {
		return x.Logout
	}
	return nil
}

type isGomokuMessage_Message interface {
	isGomokuMessage_Message()
}

type GomokuMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3,oneof"`
}

type GomokuMessage_PlaceStone struct {
	PlaceStone *PlaceStone `protobuf:"bytes,2,opt,name=place_stone,json=placeStone,proto3,oneof"`
}

type GomokuMessage_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,3,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type GomokuMessage_RequestGame struct {
	RequestGame *RequestGame `protobuf:"bytes,4,opt,name=request_game,json=requestGame,proto3,oneof"`
}

type GomokuMessage_Login struct {
	Login *LoginMessage `protobuf:"bytes,5,opt,name=login,proto3,oneof"`
}

type GomokuMessage_Logout struct {
	Logout *LogoutMessage `protobuf:"bytes,6,opt,name=logout,proto3,oneof"`
}

func (*GomokuMessage_GameState) isGomokuMessage_Message() {}

func (*GomokuMessage_PlaceStone) isGomokuMessage_Message() {}

func (*GomokuMessage_GameStart) isGomokuMessage_Message() {}

func (*GomokuMessage_RequestGame) isGomokuMessage_Message() {}

func (*GomokuMessage_Login) isGomokuMessage_Message() {}

func (*GomokuMessage_Logout) isGomokuMessage_Message() {}

var File_Gomoku_proto protoreflect.FileDescriptor

var file_Gomoku_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x47, 0x6f, 0x6d, 0x6f, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x6f, 0x6d, 0x6f, 0x6b, 0x75, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x7e,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x75, 0x72,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x54, 0x75, 0x72, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x47, 0x61,
	0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x57,
	0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f,
	0x6d, 0x6f, 0x6b, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77,
	0x68, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xd2, 0x02, 0x0a, 0x0d, 0x47, 0x6f, 0x6d, 0x6f, 0x6b, 0x75, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6d, 0x6f, 0x6b, 0x75,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x6f, 0x6d, 0x6f, 0x6b, 0x75, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x6e, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x6e, 0x65, 0x12, 0x32,
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6d, 0x6f, 0x6b, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x6d, 0x6f, 0x6b,
	0x75, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6d, 0x6f, 0x6b, 0x75, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2f, 0x0a, 0x06, 0x6c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x6d,
	0x6f, 0x6b, 0x75, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x4f, 0x6d, 0x6f, 0x6b, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Gomoku_proto_rawDescOnce sync.Once
	file_Gomoku_proto_rawDescData = file_Gomoku_proto_rawDesc
)

func file_Gomoku_proto_rawDescGZIP() []byte {
	file_Gomoku_proto_rawDescOnce.Do(func() {
		file_Gomoku_proto_rawDescData = protoimpl.X.CompressGZIP(file_Gomoku_proto_rawDescData)
	})
	return file_Gomoku_proto_rawDescData
}

var file_Gomoku_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Gomoku_proto_goTypes = []any{
	(*Position)(nil),      // 0: gomoku.Position
	(*GameState)(nil),     // 1: gomoku.GameState
	(*PlaceStone)(nil),    // 2: gomoku.PlaceStone
	(*GameStart)(nil),     // 3: gomoku.GameStart
	(*RequestGame)(nil),   // 4: gomoku.RequestGame
	(*LoginMessage)(nil),  // 5: gomoku.LoginMessage
	(*LogoutMessage)(nil), // 6: gomoku.LogoutMessage
	(*GomokuMessage)(nil), // 7: gomoku.GomokuMessage
}
var file_Gomoku_proto_depIdxs = []int32{
	0, // 0: gomoku.PlaceStone.position:type_name -> gomoku.Position
	1, // 1: gomoku.GomokuMessage.game_state:type_name -> gomoku.GameState
	2, // 2: gomoku.GomokuMessage.place_stone:type_name -> gomoku.PlaceStone
	3, // 3: gomoku.GomokuMessage.game_start:type_name -> gomoku.GameStart
	4, // 4: gomoku.GomokuMessage.request_game:type_name -> gomoku.RequestGame
	5, // 5: gomoku.GomokuMessage.login:type_name -> gomoku.LoginMessage
	6, // 6: gomoku.GomokuMessage.logout:type_name -> gomoku.LogoutMessage
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_Gomoku_proto_init() }
func file_Gomoku_proto_init() {
	if File_Gomoku_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Gomoku_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PlaceStone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RequestGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LoginMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LogoutMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gomoku_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GomokuMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Gomoku_proto_msgTypes[7].OneofWrappers = []any{
		(*GomokuMessage_GameState)(nil),
		(*GomokuMessage_PlaceStone)(nil),
		(*GomokuMessage_GameStart)(nil),
		(*GomokuMessage_RequestGame)(nil),
		(*GomokuMessage_Login)(nil),
		(*GomokuMessage_Logout)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Gomoku_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Gomoku_proto_goTypes,
		DependencyIndexes: file_Gomoku_proto_depIdxs,
		MessageInfos:      file_Gomoku_proto_msgTypes,
	}.Build()
	File_Gomoku_proto = out.File
	file_Gomoku_proto_rawDesc = nil
	file_Gomoku_proto_goTypes = nil
	file_Gomoku_proto_depIdxs = nil
}
